version: '2'
services:

  nginx:
    build: ./nginx
    image: comoyi/nginx:0.0.1
    ports:
      - 80:80
    volumes:
      - ./data:/data
      - ./data/conf/nginx:/etc/nginx
      - ./data/www:/var/www/html
      - ./data/log/nginx:/var/log/nginx

  redis:
    build: ./redis
    image: comoyi/redis:0.0.1
    ports:
      - 6379:6379

  php-fpm:
    build: ./php-fpm
    image: comoyi/php-fpm:0.0.1
    ports:
      - 9000:9000
    volumes:
      - ./data:/data
      - ./data/www:/var/www/html
      - ./data/log/php-fpm:/var/log/php

  php-cli:
    build: ./php-cli
    image: comoyi/php-cli:0.0.1
