version: '3'

services:

# php56-fpm

  php56-fpm:
    build:
      context: ./php56-fpm
    image: comoyi/php56-fpm:0.0.1
    ports:
      - ${PHP56_PORT}:9000
    volumes:
      - ./php56-fpm/conf:/usr/local/etc:ro
      - ${CODE_PATH}:/var/www/html
      - ${LOG_PATH}/php-fpm:/var/log/php

# php-fpm

  php-fpm:
    build:
      context: ./php-fpm
    image: comoyi/php-fpm:0.0.1
    ports:
      - ${PHP_PORT}:9000
    volumes:
      - ./php-fpm/conf:/usr/local/etc:ro
      - ${CODE_PATH}:/var/www/html
      - ${LOG_PATH}/php-fpm:/var/log/php

# php71-fpm

  php71-fpm:
    build:
      context: ./php71-fpm
    image: comoyi/php71-fpm:0.0.1
    ports:
      - ${PHP71_PORT}:9000
    volumes:
      - ./php71-fpm/conf:/usr/local/etc:ro
      - ${CODE_PATH}:/var/www/html
      - ${LOG_PATH}/php71-fpm:/var/log/php

# php72-fpm

  php72-fpm:
    build:
      context: ./php72-fpm
    image: comoyi/php72-fpm:0.0.1
    ports:
      - ${PHP72_PORT}:9000
    volumes:
      - ./php72-fpm/conf:/usr/local/etc:ro
      - ${CODE_PATH}:/var/www/html
      - ${LOG_PATH}/php72-fpm:/var/log/php

# nginx

  nginx:
    build:
      context: ./nginx
    image: comoyi/nginx:0.0.1
    ports:
      - ${NGINX_HTTP_PORT}:80
    depends_on:
      - php56-fpm
      - php-fpm
      - php71-fpm
      - php72-fpm
    volumes:
      - ./nginx/conf:/etc/nginx:ro
      - ${CODE_PATH}:/var/www/html
      - ${LOG_PATH}/nginx:/var/log/nginx

# redis

  redis:
    build:
      context: ./redis
    image: comoyi/redis:0.0.1
    ports:
      - ${REDIS_PORT}:6379

# mysql

  mysql:
    build:
      context: ./mysql
    image: comoyi/mysql:0.0.1
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ${MYSQL_CONF_PATH}:/etc/mysql/conf.d
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

# rabbitmq

  rabbitmq:
    build:
      context: ./rabbitmq
    image: comoyi/rabbitmq:0.0.1
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_MANAGEMENT_PORT}:15672
