version: '2'

services:

# php56-fpm

  php56-fpm:
    build: ./php56-fpm
    image: comoyi/php56-fpm:0.0.1
    ports:
      - ${PHP56_PORT}:9000
    volumes:
      - ./php56-fpm/conf:/usr/local/etc:ro
      - ${CODE_PATH}:/var/www/html
      - ${LOG_PATH}/php-fpm:/var/log/php

# php-fpm

  php-fpm:
    build: ./php-fpm
    image: comoyi/php-fpm:0.0.1
    ports:
      - ${PHP_PORT}:9000
    volumes:
      - ./php-fpm/conf:/usr/local/etc:ro
      - ${CODE_PATH}:/var/www/html
      - ${LOG_PATH}/php-fpm:/var/log/php

# nginx

  nginx:
    build: ./nginx
    image: comoyi/nginx:0.0.1
    ports:
      - ${NGINX_HTTP_PORT}:80
    depends_on:
      - php56-fpm
      - php-fpm
    volumes:
      - ./nginx/conf:/etc/nginx:ro
      - ${CODE_PATH}:/var/www/html
      - ${LOG_PATH}/nginx:/var/log/nginx

# redis

  redis:
    build: ./redis
    image: comoyi/redis:0.0.1
    ports:
      - ${REDIS_PORT}:6379

# mysql

  mysql:
    build: ./mysql
    image: comoyi/mysql:0.0.1
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

# rabbitmq

  rabbitmq:
    build: ./rabbitmq
    image: comoyi/rabbitmq:0.0.1
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_MANAGEMENT_PORT}:15672