version: '2'

services:

# php56-fpm

  php56-fpm:
    build: ./php56-fpm
    image: comoyi/php56-fpm:0.0.1
    ports:
      - 50201:9000
    volumes:
      - ./php56-fpm/conf:/usr/local/etc:ro
      - ${CODE_PATH}:/var/www/html
      - ${LOG_PATH}/php-fpm:/var/log/php

# php-fpm

  php-fpm:
    build: ./php-fpm
    image: comoyi/php-fpm:0.0.1
    ports:
      - 50202:9000
    volumes:
      - ./php-fpm/conf:/usr/local/etc:ro
      - ${CODE_PATH}:/var/www/html
      - ${LOG_PATH}/php-fpm:/var/log/php

# nginx

  nginx:
    build: ./nginx
    image: comoyi/nginx:0.0.1
    ports:
      - 80:80
    volumes:
      - ./nginx/conf:/etc/nginx:ro
      - ${CODE_PATH}:/var/www/html
      - ${LOG_PATH}/nginx:/var/log/nginx

# redis

  redis:
    build: ./redis
    image: comoyi/redis:0.0.1
    ports:
      - 50501:6379
