version: '2'

services:

# nginx

  nginx:
    build: ./nginx
    image: comoyi/nginx:0.0.1
    ports:
      - 80:80
    volumes:
      - ./nginx/conf:/etc/nginx:ro
      - ${DATA_PATH}/www:/var/www/html
      - ${DATA_PATH}/log/nginx:/var/log/nginx

# redis

  redis:
    build: ./redis
    image: comoyi/redis:0.0.1
    ports:
      - 50501:6379

# php-fpm-56

  php-fpm-56:
    build: ./php-fpm-56
    image: comoyi/php-fpm-56:0.0.1
    ports:
      - 50202:9000
    volumes:
      - ${DATA_PATH}/www:/var/www/html
      - ${DATA_PATH}/log/php-fpm:/var/log/php

# php-fpm

  php-fpm:
    build: ./php-fpm
    image: comoyi/php-fpm:0.0.1
    ports:
      - 50201:9000
    volumes:
      - ./php-fpm/conf:/usr/local/etc:ro
      - ${DATA_PATH}/www:/var/www/html
      - ${DATA_PATH}/log/php-fpm:/var/log/php
